
/* covers.c  :  5 Dec 24 .. 10 Dec 24  :  Colin Ramsay */

/* Ex
desk4-OptiPlex-9020/EXWORK/PC00328/Orig30Jun09/Archive1/poly/enum/enum2.c
MyWork/tiles.c
*/

/**
  Enumerating fixed polyominoes of size P (cf. tiles.c) is the first step in
generating all polyomino covers of the PxP square.  This works, but the scaling
is VERY bad.  We 'know' that t(n) grows as $n^{n^2}$.  If we wish to generate
and process all covers, P=7 is probably the limit.  We can generate the cover up
to P=6 on-the-fly, but for P=7 we'll have to store them in a (big) file.
**/

#include <stdio.h>  /* printf() ... */
#include <stdlib.h> /* EXIT_SUCCESS ... */
#include <time.h>   /* time() ... */

#include "exact.h" /* for libexact */

#include <stdint.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

#define True 1
#define False 0

#define P 7 /* `target' tile size */

#define Pmin 1
#define Pmax P*P

int tile[P][2]; /* the tile's x/y coords */
int t[P + 1];   /* count of (fixed) tiles */

int cofp, copp, covp; /* counts FixedPoly, PolyPosition, ValidPos'n */
int codc;             /* counts of DistinctCov */

/* Note that x can run from -(P-2) to +(P-1) and y can run from 0 to +(P-1).
With a 1 wide guard all round, we need -(P-1) .. +P and -1 .. +P.  So the
indexing offsets are +(P-1) & +1.  We use -P as an end-of-stack value, since
it's never used. */

int freept[2 * P][P + 2];    /* the free points - boolean */
int succpt[2 * P][P + 2][2]; /* the successor points - x/y */

#define Xoff (P - 1)
#define Yoff 1
#define Eos -P

/* PxP array for the current dissection, aka polyomino cover, aka tiling.  The
tiles are labelled arbitrarily 0..P-1. */

int tiling[P][P];

/* Poly struct stores the P cell numbers (0 to P^2-1) of a fixed polyomino in
the PxP grid (aka tile), in some order.  A simple linked-list is used.
TBA: dammit, need to lookup a Poly's cells. can we query the DLX array! */

typedef struct Poly {
  struct Poly *next;
  int cells[P];
  uint64_t mask;
  uint64_t deductions;
} Poly;

Poly *heads[Pmax];        // Basic divided up version of tHead
Poly *heads3[Pmax][2][3]; // Divided up version of tHead

uint64_t *heads64[Pmax][2]
                 [3]; // Array version of heads3 that only stores the bit-masks

int headsIndex[Pmax][2][3] = {
    0}; // how long each array in heads64 is at the given index

uint64_t startHeads[36][8]; // Arrays of each bit-mask that occupies the
                            // bottom-right corner

int totalPolys =
    0; // How many valid polyomino placements there are for the given P

Poly *tHead, *tTail;

Poly *newPoly(void) {
  Poly *ptr;
  if ((ptr = (Poly *)malloc(sizeof(Poly))) == NULL) {
    printf("** Unable to malloc Poly struct in newPoly() **\n");
    exit(EXIT_FAILURE);
  }
  ptr->next = NULL;
  return ptr;
}

/*
 * Performs a DFS search from the first 0 in the given string of binary.
 * If the result is not a multiple of P, the fixed polynomial placement is
 * invalid. solution is modified from a solution generated by AI using the
 * prompt "If I had a string that was representing a NxN grid (e.g. 010110000
 * for N = 3), how could I write a function that uses depth first search to find
 * the number of reachable 0s starting from the first 0 in the string?"
 *
 * @string: bit-mask of polyomino placement in the form of an array of
 * characters.
 *
 * @x: start grid column for dfs.
 *
 * @y: start grid row for dfs.
 *
 * @return: how many empty cells were found from the starting position.
 */

int visited[P][P];
int dx[] = {-1, 1, 0, 0};
int dy[] = {0, 0, -1, 1};

int dfs(char *string, int x, int y) {

  if (x < 0 || x >= P || y < 0 || y >= P) {
    return 0;
  }

  if (visited[x][y]) {
    return 0;
  }
  if (string[x * P + y] != '0') {
    return 0;
  }
  visited[x][y] = 1;

  int count = 1;

  for (int dir = 0; dir < 4; dir++) {
    int nx = x + dx[dir];
    int ny = y + dy[dir];
    count += dfs(string, nx, ny);
  }

  return count;
}

/*
 * Uses the dfs function above to check whether
 * or not a given polyomino placement on the grid is valid.
 *
 * @string: bit-mask of polyomino placement in the form of an array of
 * characters.
 *
 * @return: -1 if grid is full, otherwise the number of
 *   empty cells that were found from the first empty cell found
 */
int poly_valid(char *string) {
  int start = -1;
  for (int i = 0; i < Pmax; i++) {
    if (string[i] == '0') {
      start = i;
      break;
    }
  }

  if (start == -1) {
    return 0;
  }

  memset(visited, 0, sizeof(visited));

  int start_x = start / P;
  int start_y = start % P;

  int total = dfs(string, start_x, start_y);

  return total;
}

/*
 * Modified verson of the dfs function above so that
 * it can check the validity of multiple polyomino placements on the grid.
 *
 * Modified the function myself, then used ChatGPT to make it more efficient
 * with the prompt: "Can you see how to make this function more efficient in
 * terms of speed?"
 *
 * @mask: the 64 bit-mask of the polyomino placement.
 *
 * @visited: how much of the mask has already been checked in the dfs process.
 *
 * @pos: starting position for the dfs process.
 *
 * @return: total number of empty cells found from the starting position.
 */
int dxMul[] = {-1, 1, 0, 0};
int dyMul[] = {0, 0, -1, 1};

int dfs_multi_mask(uint64_t mask, uint64_t *visited, int pos) {
  if (*visited & (1ULL << pos))
    return 0;
  if (mask & (1ULL << pos))
    return 0;

  *visited |= (1ULL << pos);

  int count = 1;

  int x = pos / P;
  int y = pos % P;

  if (x > 0) {
    count += dfs_multi_mask(mask, visited, pos - P);
  };
  if (x < P - 1) {
    count += dfs_multi_mask(mask, visited, pos + P);
  };
  if (y > 0) {
    count += dfs_multi_mask(mask, visited, pos - 1);
  };
  if (y < P - 1) {
    count += dfs_multi_mask(mask, visited, pos + 1);
  };

  return count;
}

/*
 * Modified version of the poly_valid function above to check the validy of
 * multiple polyomino placements on the grid.
 *
 * Modifies the function myself, then used ChatGPT to make the function faster
 * with the prompt: "Can you see how to make this function more efficient in
 * terms of speed?"
 *
 * @mask: 64 bit-mask of a polyomino placement
 *
 * @return: 0 if placement is invalid, otherwise how many empty cells were found
 * on the grid.
 */
int poly_valid_multi_mask(uint64_t mask) {
  uint64_t visited = 0;
  int total = 0;

  if ((mask & (0xFFFFFFFFFFFFFFFF >> (64 - Pmax))) ==
      (0xFFFFFFFFFFFFFFFF >> (64 - Pmax))) {
    return 1;
  }

  for (int i = 0; i < Pmax; i++) {
    if (!(mask & (1ULL << i)) && !(visited & (1ULL << i))) {
      int size = dfs_multi_mask(mask, &visited, i);
      total += size;

      if (total % P != 0)
        return 0;
    }
  }

  return total;
}

/*
 * Creates a 64 bit-mask of a given polyomino placement on the grid from
 * a given array of the indexes of the cells the polyomino occupies on the grid.
 *
 * @cells: array of the indexes of cells that are occupied by a given polyomino.
 *
 * @return: a 64 bit-mask equivalent of the given cells array.
 */
uint64_t make_mask(int cells[P]) {
  uint64_t mask = 0;
  for (int i = 0; i < P; i++) {
    mask |= (1ULL << cells[i]);
  }
  return mask;
}

/*
  Takes tHead/tTail and builds new list of all possible positions of all fixed
polyominoes (these are NOT checked for validity at this stage).  This list
'replaces' the original.  The positions are straightforward.  For each fixed
Poly the top row & left col are both 0 (by construction), we need bottomrow &
rightcolumn (br, rc).  Now easy to generate all possible placements.
  Note that the original tHead/tTail list will be 'replaced' by the new list,
with each of the original fixed Poly being followed by its 'children' (some of
which may be 'invalid').  The original list ie deallocated as we go.
*/

void genPosn(void) {
  Poly *ptr, *newH, *newT, *pTmp; /* NB: pTmp does double duty! */
  int br, rc;
  int i, j, k, r, c;

  newH = newT = NULL;
  pTmp = NULL;

  for (ptr = tHead; ptr != NULL; ptr = ptr->next) {
    if (pTmp != NULL) {
      free(pTmp);
    }

    /* Get the tile's bounding rectangle */
    br = 0;
    rc = 0;
    for (i = 0; i < P; i++) {
      j = ptr->cells[i];
      if (j / P > br) {
        br = j / P;
      }
      if (j % P > rc) {
        rc = j % P;
      }
    }
    /*printf("br=%d rc=%d\n", br, rc);*/

    /* Iterate over all possible positions, incl the 'fixed' position */
    for (r = 0; r < P - br; r++) {
      for (c = 0; c < P - rc; c++) {
        pTmp = newPoly();
        for (k = 0; k < P; k++) {
          pTmp->cells[k] = ptr->cells[k] + r * P + c;
        }
        copp++;
        // printf("Position %d\n", copp-1);
        // prtCells(pTmp);

        if (newH == NULL) {
          newH = newT = pTmp;
        } else {
          newT->next = pTmp;
          newT = pTmp;
        }
        pTmp = NULL;
      }
    }

    pTmp = ptr;
  }

  if (pTmp != NULL) {
    free(pTmp);
  }
  tHead = newH;
  tTail = newT;
}

/**
  Function logTile() processes the new current tile[P][2], of size P.
  In the tiles.c code, cell's coords are (X,Y) with the origin (0,0) and X incr
to the right and Y upwards.  For fixed polyominoes in the PxP square the ref'ce
position is as far up and to the left as possible.  The coords are (R,C) with
the origin (0,0) and C incr to the right and R downwards.  So X becomes C and Y
becomes R.  The least X has to become C=0: ie, C = X - min(set of X).  We have
to invert the order for Y, with the maximum Y becoming R = 0.
  With the polyomino in our standard position we convert the xP R/C coord pairs
to cell numbers (in 0..P^2-1) and add it to our linked list of "fixed
polyominoes in reference position".  Note that the cell numbers may not be in
incr order (this does not matter?).
**/

void logTile(int tsiz) {
  int i, x, y, r, c;
  int minX = P, maxY = -1;
  Poly *ptr;

  /*printf("# %2d : X/Y ", t[tsiz]);*/
  for (i = 0; i < tsiz; i++) {
    x = tile[i][0];
    y = tile[i][1];
    /*printf(" (%d,%d)", x, y);*/
    if (x < minX) {
      minX = x;
    }
    if (y > maxY) {
      maxY = y;
    }
  }
  /*printf(" : minX=%d maxY=%d\n", minX, maxY);*/

  ptr = newPoly();

  /*printf("# %2d : R/C ", t[tsiz]);*/
  for (i = 0; i < tsiz; i++) {
    x = tile[i][0];
    y = tile[i][1];
    c = x - minX;
    r = maxY - y;
    /*printf(" (%d,%d)", r, c);*/
    ptr->cells[i] = r * P + c;
  }

  /*printf("\n");*/

  if (tHead == NULL) {
    tHead = tTail = ptr;
  } else {
    tTail->next = ptr;
    tTail = ptr;
  }

  /*prtTile();*/
  /*prtCells(ptr);*/
}

/* tsiz is the size of the current tile at entry, and is thus the index for the
point(s) to be added.  x/y are the point at the head of the untried stack. */

void recurse(int tsiz, int x, int y) {
  int ix, iy, tx, ty, cx, cy;
  int tl, tr, tu, td;

  /* Repeat until the untried set is exhausted ... */

  ix = x;
  iy = y;
  while (ix != Eos && iy != Eos) {

    /* 1. Remove an (arbitrary) element from the untried set ... */

    cx = succpt[ix + Xoff][iy + Yoff][0];
    cy = succpt[ix + Xoff][iy + Yoff][1];

    /* 2. Place a cell at this point ... */

    tile[tsiz][0] = ix;
    tile[tsiz][1] = iy;

    /* 3. Count this new polynomio, process if size P ... */

    t[tsiz + 1]++;

    if (tsiz == P - 1) {
      /*printf("\n");*/
      logTile(tsiz + 1);
    }

    /* 4. If the size is less than P ... */

    if (tsiz < P - 1) {

      /* (a) Add *new* neighbours to the untried set ... */

      if (freept[ix + Xoff][iy + Yoff + 1]) {
        succpt[ix + Xoff][iy + Yoff + 1][0] = cx;
        succpt[ix + Xoff][iy + Yoff + 1][1] = cy;
        cx = ix;
        cy = iy + 1;

        freept[cx + Xoff][cy + Yoff] = False;
        tu = True;
      } else {
        tu = False;
      }
      if (freept[ix + Xoff + 1][iy + Yoff]) {
        succpt[ix + Xoff + 1][iy + Yoff][0] = cx;
        succpt[ix + Xoff + 1][iy + Yoff][1] = cy;
        cx = ix + 1;
        cy = iy;

        freept[cx + Xoff][cy + Yoff] = False;
        tr = True;
      } else {
        tr = False;
      }
      if (freept[ix + Xoff - 1][iy + Yoff]) {
        succpt[ix + Xoff - 1][iy + Yoff][0] = cx;
        succpt[ix + Xoff - 1][iy + Yoff][1] = cy;
        cx = ix - 1;
        cy = iy;

        freept[cx + Xoff][cy + Yoff] = False;
        tl = True;
      } else {
        tl = False;
      }
      if (freept[ix + Xoff][iy + Yoff - 1]) {
        succpt[ix + Xoff][iy + Yoff - 1][0] = cx;
        succpt[ix + Xoff][iy + Yoff - 1][1] = cy;
        cx = ix;
        cy = iy - 1;

        freept[cx + Xoff][cy + Yoff] = False;
        td = True;
      } else {
        td = False;
      }

      /* (b) Call this algorithm recursively ... */

      recurse(tsiz + 1, cx, cy);

      /* (c) Remove the new neighbours from the untried set ... */

      if (td) {
        freept[cx + Xoff][cy + Yoff] = True;

        tx = succpt[cx + Xoff][cy + Yoff][0];
        ty = succpt[cx + Xoff][cy + Yoff][1];
        cx = tx;
        cy = ty;
      }
      if (tl) {
        freept[cx + Xoff][cy + Yoff] = True;

        tx = succpt[cx + Xoff][cy + Yoff][0];
        ty = succpt[cx + Xoff][cy + Yoff][1];
        cx = tx;
        cy = ty;
      }
      if (tr) {
        freept[cx + Xoff][cy + Yoff] = True;

        tx = succpt[cx + Xoff][cy + Yoff][0];
        ty = succpt[cx + Xoff][cy + Yoff][1];
        cx = tx;
        cy = ty;
      }
      if (tu) {
        freept[cx + Xoff][cy + Yoff] = True;

        tx = succpt[cx + Xoff][cy + Yoff][0];
        ty = succpt[cx + Xoff][cy + Yoff][1];
        cx = tx;
        cy = ty;
      }
    }

    /* 5. Remove newest cell ... */

    /* n/a */

    tx = succpt[ix + Xoff][iy + Yoff][0];
    ty = succpt[ix + Xoff][iy + Yoff][1];
    ix = tx;
    iy = ty;
  }
}

/*
 * Converts a given polyomino placement into a string of 0s and 1s for a
 * binary representation of the given polyomino.
 *
 * @cells: array of the indexes of cells that are occupied by a given polyomino.
 *
 * @return pointer to an array of chars that is the binary representation of the
 * polyomino placement.
 */
char *int_to_binary(int cells[P]) {
  char *binary = malloc(Pmax * sizeof(char));
  if (!binary) {
    return NULL;
  }

  for (int i = 0; i < Pmax; i++) {
    binary[i] = '0';
  }

  for (int i = 0; i < P; i++) {
    binary[cells[i]] = '1';
  }

  return binary;
}

/*
 * Swap sorts a polyomino's array of cell indexes into ascending order.
 *
 * @cells: array of the indexes of cells that are occupied by a given polyomino.
 */
void sort_cells(int cells[P]) {
  for (int i = 0; i < P - 1; i++) {
    for (int j = i + 1; j < P; j++) {
      if (cells[j] < cells[i]) {
        int temp = cells[i];
        cells[i] = cells[j];
        cells[j] = temp;
      }
    }
  }
}

/*
 * Iterates through the generated linked list of polyomino placements
 * and removes the ones that are invalid placements from the list.
 *
 * @head: a linked list of Poly structs.
 *
 * @return: head but with any invalid polyomino placements removed.
 */
Poly *pruning(struct Poly *head) {
  struct Poly *current = head;
  struct Poly *prev = NULL;
  int count = 0;
  while (current != NULL) {
    current->mask = make_mask(current->cells);
    sort_cells(current->cells);
    char *binaryRep = int_to_binary(current->cells);
    if (poly_valid(binaryRep) % P != 0) {
      if (prev != NULL) {
        prev->next = current->next;
      } else {
        prev = current->next;
      }
      Poly *now = current;
      current = current->next;
      free(now);
    } else {
      prev = current;
      current = current->next;
      count++;
    }
    free(binaryRep);
  }
  totalPolys = count;
  return head;
}

/*
 * Similar to the pruning function above, but only checks a single polyomino
 * place from its mask.
 *
 * @mask: 64 bit-mask of the given partial grid cover.
 *
 * @return: 0 if partial cover is invalid, 1 otherwise.
 */
int prune(uint64_t mask) {
  char grid[Pmax];
  for (int i = 0; i < Pmax; i++) {
    if ((mask & (1ULL << i)) != 0) {
      grid[i] = '1';
    } else {
      grid[i] = '0';
    }
  }
  int pruned = poly_valid(grid);
  if (pruned % P != 0) {
    return 0;
  } else {
    return 1;
  }
}

/*
 * More efficent version of the prune function above.
 *
 * @mask: 64 bit-mask of the given partial grid cover.
 *
 * @return: 0 if partial cover is invalid, 1 otherwise.
 */
int prune_multi(uint64_t mask) {

  int total = poly_valid_multi_mask(mask);
  if (total) {
    return 1;
  }
  return 0;
}

/*
 * Inserts a polyomino into a linked list of polyominoes.
 *
 * @head: pointer to the head of the linked list that the new Poly struct is
 * being added to.
 *
 * @new_node: new Poly struct to become the new head of the given linked list.
 */
void insert_front(Poly **head, Poly *new_node) {
  new_node->next = *head;
  *head = new_node;
}

/*
 * Handles deductions by comparing every Poly pos in the list that
 * makes a corner with the edge of the grid with every Poly pos that can fill
 * that corner. If there is only one, a deduction has been found.
 *
 * This function doesn't really work, I found a bug and didn't get around to
 * fixing it :(
 */
void deduction() {
  Poly *current = tHead;
  int dedCount = 0;

  while (current != NULL) {
    uint64_t tempMask = 0;
    // Check current for border corners
    for (int i = 0; i < P; i++) {
      int corner1 = -1;
      int corner2 = -1;
      int checkCell = current->cells[i];
      if (checkCell >= Pmax - P) {
        if (checkCell == Pmax - 1) {
          corner1 = Pmax - P - 1;
          corner2 = Pmax - 2;
        } else if (checkCell == Pmax - P) {
          corner1 = checkCell - P;
          corner2 = Pmax - P + 1;
        } else {
          corner1 = checkCell + 1;
          corner2 = checkCell - 1;
        }
      } else if (current->cells[i] < P) {
        if (checkCell == P - 1) {
          corner1 = checkCell + P;
          corner2 = P - 2;
        } else if (checkCell == 0) {
          corner1 = P;
          corner2 = 1;
        } else {
          corner1 = checkCell + 1;
          corner2 = checkCell - 1;
        }
      } else if (current->cells[i] % P == 0) {
        corner1 = checkCell + P;
        corner2 = checkCell - P;
      } else if (current->cells[i] % P == (P - 1)) {
        corner1 = checkCell + P;
        corner2 = checkCell - P;
      }

      if (corner1 != -1 && corner2 != -1) {

        if ((current->mask & (1ULL << corner1)) != 0 &&
            (current->mask & (1ULL << corner2)) != 0) {
          continue;
        }

        Poly *checker = tHead;
        while (checker != NULL) {
          if ((checker->mask & (1ULL << corner1)) != 0 ||
              (checker->mask & (1ULL << corner2)) != 0) {
            if ((current->mask & checker->mask) == 0) {
              if (!prune((current->mask | checker->mask))) {
                checker = checker->next;
                continue;
              } else if (tempMask == 0) {
                tempMask = current->mask | checker->mask;
              } else {
                tempMask = 0;
                break;
              }
            }
          }
          checker = checker->next;
        }
        if (tempMask != 0) {
          current->deductions = tempMask;
          dedCount++;
          tempMask = 0;
        }
      }
    }
    current = current->next;
  }
  printf("total deductions found: %d\n", dedCount);
}

/*
 * Bucket sorts the initial linked list of polyominoes into separate arrays
 * based on their smallest cell index.
 */
void build_heads() {
  for (int i = 0; i < Pmax; i++)
    heads[i] = NULL;

  Poly *current = tHead;
  int counter = 0;
  while (current != NULL) {
    Poly *next = current->next;

    int idx = current->cells[0]; // bucket by first cell
    if (idx < 0 || idx >= Pmax) {
      printf("Warning: invalid cell index %d\n", idx);
      current = next;
      continue;
    }

    current->next = NULL; // detach node from original list
    if (heads[idx] == NULL) {
      heads[idx] = current;
    } else {
      insert_front(&heads[idx], current);
    }

    counter++;
    current = next;
  }
  printf("Total polys bucketed: %d\n", counter);
}

/*
 * Bucket sorts the initial linked list of polyominoes into separate arrays
 * based on their smallest cell index and logical deductions that can be made
 * from that.
 *
 * Additionally, also counts how many polyominos go into each linked list for
 * headsIndex.
 *
 * e.g. For the smallest cell that the polyomino occupies, it must also occupy
 *     the cell to its left, the cell directly above, or both.
 */
void build_heads3() {
  for (int i = 0; i < Pmax; i++) {
    heads3[i][0][0] = NULL;
    heads3[i][0][1] = NULL;
    heads3[i][0][2] = NULL;
    heads3[i][1][0] = NULL;
    heads3[i][1][1] = NULL;
    heads3[i][1][2] = NULL;
  }
  Poly *current = tHead;
  int counter = 0;

  while (current != NULL) {
    Poly *next = current->next;
    current->next = NULL;

    int idx = current->cells[0];
    if (idx < 0 || idx >= Pmax) {
      printf("Warning: invalid cell index %d\n", idx);
      current = next;
      continue;
    }
    if (current->cells[1] == (idx + 1)) {
      if (idx % P < P - 2 && current->cells[2] == (idx + 2)) {
        if (heads3[idx][0][0] == NULL) {
          heads3[idx][0][0] = current;
          headsIndex[idx][0][0]++;
        } else {
          insert_front(&heads3[idx][0][0], current);
          headsIndex[idx][0][0]++;
        }
      } else {
        for (int i = 0; i < P; i++) {
          if (current->cells[i] == idx + P + 1) {
            if (heads3[idx][0][1] == NULL) {
              heads3[idx][0][1] = current;
              headsIndex[idx][0][1]++;
            } else {
              insert_front(&heads3[idx][0][1], current);
              headsIndex[idx][0][1]++;
            }
            break;
          } else if (current->cells[i] == idx + P) {
            if (heads3[idx][0][2] == NULL) {
              heads3[idx][0][2] = current;
              headsIndex[idx][0][2]++;
            } else {
              insert_front(&heads3[idx][0][2], current);
              headsIndex[idx][0][2]++;
            }
            break;
          }
        }
      }
    } else {
      for (int i = 0; i < P; i++) {
        if (idx % P != P - 1 && current->cells[i] == idx + P + 1) {
          if (heads3[idx][1][0] == NULL) {
            heads3[idx][1][0] = current;
            headsIndex[idx][1][0]++;
          } else {
            insert_front(&heads3[idx][1][0], current);
            headsIndex[idx][1][0]++;
          }
          break;
        } else if (current->cells[i] == idx + 2 * P) {
          if (heads3[idx][1][1] == NULL) {
            heads3[idx][1][1] = current;
            headsIndex[idx][1][1]++;
          } else {
            insert_front(&heads3[idx][1][1], current);
            headsIndex[idx][1][1]++;
          }
          break;
        } else if (idx % P != 0 && current->cells[i] == idx + P - 1) {
          if (heads3[idx][1][2] == NULL) {
            heads3[idx][1][2] = current;
            headsIndex[idx][1][2]++;
          } else {
            insert_front(&heads3[idx][1][2], current);
            headsIndex[idx][1][2]++;
          }
          break;
        }
      }
    }
    counter++;
    current = next;
  }
}

/*
 * Iterates through the headsIndex arrays and allocates space in
 * the heads64 arrays at the same index with the length stored in headsIndex at
 * that index.
 */
void allocate_heads64() {
  for (int i = 0; i < Pmax; i++) {
    for (int j = 0; j < 2; j++) {
      for (int k = 0; k < 3; k++) {
        int count = headsIndex[i][j][k];
        if (count > 0) {
          heads64[i][j][k] = (uint64_t *)malloc(count * sizeof(uint64_t));
          if (heads64[i][j][k] == NULL) {
            fprintf(stderr, "Memory allocation failed at [%d][%d][%d]\n", i, j,
                    k);
            exit(EXIT_FAILURE);
          }
        } else {
          heads64[i][j][k] = NULL;
        }
      }
    }
  }
}

/*
 * Iterates through the heads3 linked lists and
 * populates the heads64 array at the same index
 * with the masks of the polyominoes in that linked list.
 */
void populate_heads64() {
  for (int i = 0; i < Pmax; i++) {
    for (int j = 0; j < 2; j++) {
      for (int k = 0; k < 3; k++) {
        Poly *current = heads3[i][j][k];
        uint64_t *array = heads64[i][j][k];
        int idx = 0;
        while (current != NULL) {
          array[idx] = current->mask;
          idx++;
          current = current->next;
        }
      }
    }
  }
}

/*
 * This function is hard coded for P = 7.
 * Splits heads64[0] into 36 evenly sized arrays for optimal processor usage.
 *
 * Used ChatGPT to do this because I couldn't be assed honestly
 * Prompt: "how would you split the 6 arrays in
 * heads64[0] into 36 evenly sized arrays of 8 uint64_t integers?"
 */
void split_heads() {
  int currentSmall = 0; // which small array we're filling
  int posInSmall = 0;   // position inside current small array

  for (int a = 0; a < 6; a++) {
    uint64_t *arr = heads64[0][a / 3][a % 3]; // map 0..5 → [j][k]
    int count = headsIndex[0][a / 3][a % 3];

    for (int e = 0; e < count; e++) {
      startHeads[currentSmall][posInSmall] = arr[e];
      posInSmall++;

      if (posInSmall >= 8) {
        currentSmall++;
        posInSmall = 0;
      }
    }
  }
}

/*
 * Basic version of myGenCov for P < 4
 *
 * @start_idx: index of empty cell to start search from.
 *
 * @cover_mask: current partial cover being enumerated.
 *
 * @return: how many full covers were found.
 */
int myGenCov0(int start_idx, uint64_t cover_mask) {
  if ((cover_mask & (0xFFFFFFFFFFFFFFFF >> (64 - Pmax))) ==
      (0xFFFFFFFFFFFFFFFF >> (64 - Pmax))) {
    return 1;
  }

  int found = 0;
  for (int i = start_idx; i < Pmax; i++) { // start from current index
    if ((cover_mask & (1ULL << i)) != 0 || heads[i] == NULL) {
      continue;
    }
    Poly *current = heads[i];
    while (current != NULL) {
      uint64_t temp = cover_mask;

      if ((current->mask & temp) == 0) {
        temp = (current->mask | cover_mask);
        if (prune_multi(temp)) {
          found += myGenCov0(i + 1, temp);
        }
      }
      current = current->next;
    }
  }

  return found;
}

static const uint64_t FULL_MASK =
    (Pmax == 64) ? 0xFFFFFFFFFFFFFFFFULL : ((1ULL << Pmax) - 1);
static const int limitP = Pmax - P;
static const int limit2P = Pmax - 2 * P;

/*
 * Generates unique fixed polyomino covers and counts how many are found.
 * I made the original function, and then used ChatGPT to make it more efficient
 * with the prompt: "Can you see any ways to make this function more efficient
 * in terms of speed?"
 *
 * @start_idx: empty cell on the grid to start search for next polyomino from.
 *
 * @cover_mask: current partial cover being enumerated.
 *
 * @return: how many full covers were found from the given partial cover.
 */
uint64_t myGenCov1(int start_idx, uint64_t cover_mask) {
  if ((cover_mask & FULL_MASK) == FULL_MASK) {
    return 1;
  }
  uint64_t found = 0;

  int modP = start_idx % P;
  uint64_t bit0 = 1ULL << start_idx;
  uint64_t bit1 = 1ULL << (start_idx + 1);
  uint64_t bit2 = 1ULL << (start_idx + 2);
  uint64_t bitP = 1ULL << (start_idx + P);
  uint64_t bitP1 = 1ULL << (start_idx + P + 1);
  uint64_t bitPm1 = 1ULL << (start_idx + P - 1);
  uint64_t bit2P = 1ULL << (start_idx + 2 * P);

  int empty = (cover_mask == 0);

// Macro for array processing
#define PROCESS_ARRAY(arr, count)                                              \
  for (int idx = 0; idx < (count); idx++) {                                    \
    uint64_t m = (arr)[idx];                                                   \
    if ((m & cover_mask) == 0) {                                               \
      uint64_t temp = m | cover_mask;                                          \
      if (prune_multi(temp)) {                                                 \
        int first_zero = __builtin_ctzll(~temp);                               \
        found += myGenCov1(first_zero, temp);                                  \
      }                                                                        \
    }                                                                          \
  }

  if (empty || !(cover_mask & bit0)) {
    if (empty || !(cover_mask & bit1)) {
      if (modP < P - 2 && !(cover_mask & bit2)) {
        PROCESS_ARRAY(heads64[start_idx][0][0], headsIndex[start_idx][0][0]);
      }
      if (modP < P - 1 && start_idx < limitP && !(cover_mask & bitP1)) {
        PROCESS_ARRAY(heads64[start_idx][0][1], headsIndex[start_idx][0][1]);
      }
      if (modP < P - 1 && start_idx < limitP && !(cover_mask & bitP)) {
        PROCESS_ARRAY(heads64[start_idx][0][2], headsIndex[start_idx][0][2]);
      }
    }

    if (start_idx < limitP && !(cover_mask & bitP)) {
      if (modP < P - 1 && !(cover_mask & bitP1)) {
        PROCESS_ARRAY(heads64[start_idx][1][0], headsIndex[start_idx][1][0]);
      }
      if (start_idx < limit2P && !(cover_mask & bit2P)) {
        PROCESS_ARRAY(heads64[start_idx][1][1], headsIndex[start_idx][1][1]);
      }
      if (modP > 0 && !(cover_mask & bitPm1)) {
        PROCESS_ARRAY(heads64[start_idx][1][2], headsIndex[start_idx][1][2]);
      }
    }
  }
  return found;
}

/*
 * Built to work with myGenCov1 to work with 6 child processes.
 * Splits the work load up between each process by the 6 arrays
 * that store the polyominoes that occupy the bottom-right corner
 * of the grid since none of these can be on the grid at the same
 * time as each other and therefore no covers will be missed.
 *
 * wrote the original function myself, then used ChatGPT to make it more
 * efficient with the prompt: "Can you see any ways to make this function more
 * efficient in terms of speed?"
 *
 * @process_id: which nth child process the function is being called in.
 *
 * @return: how many full covers were found in this child process.
 */
int myGenCov2(int process_id) {
  int found = 0;
  int i = process_id / 3;
  int j = process_id % 3;

  uint64_t *arr = heads64[0][i][j]; // Array of uint64_t masks
  int count = headsIndex[0][i][j];  // Number of masks in this array

  for (int k = 0; k < count; k++) {

    uint64_t temp = arr[k];

    int first_zero = __builtin_ctzll(~temp);

    found += myGenCov1(first_zero, temp);
  }

  return found;
}

/*
 * Built to work with myGenCov1 to work with multiple child processes.
 * Splits the work load up between each process by multiple arrays
 * that store the polyominoes that occupy the bottom-right corner
 * of the grid since none of these can be on the grid at the same
 * time as each other and therefore no covers will be missed or double counted.
 *
 * wrote the original function myself, then used ChatGPT to make it more
 * efficient with the prompt: "Can you see any ways to make this function more
 * efficient in terms of speed?"
 *
 * @process_id: which nth child process the function is being called in.
 *
 * @return: how many full covers were found in this child process.
 */
int myGenCov3(int process_id) {
  int found = 0;

  uint64_t *arr = startHeads[process_id];
  int count = 8; // this is hard coded for P = 7 with 36 child processes

  if (!arr)
    return 0;

  for (int k = 0; k < count; k++) {
    if (arr[k] == 0) {
      continue;
    }
    uint64_t temp = arr[k];
    int first_zero = __builtin_ctzll(~temp);
    found += myGenCov1(first_zero, temp);
  }

  return found;
}

int main(void) {
  int coverCount = 0;
  int i, x, y;
  clock_t t1, t2;

  if (P < Pmin || P > Pmax) {
    printf("\n** tile size must be in %d-%d **\n\n", Pmin, Pmax);
    exit(EXIT_FAILURE);
  }

  t1 = clock();

  printf("\n** Generating the fixed polyominoes **\n\n");

  printf("Tile size = %d\n", P);

  for (i = 1; i <= P; i++) {
    t[i] = 0;
  }

  for (x = -P + 1; x <= P; x++) {
    for (y = -1; y <= P; y++) {
      if (y >= 0 && x >= 0 && x <= P - 1 - y) {
        freept[x + Xoff][y + Yoff] = True;
      } else if (y >= 1 && x < 0 && x >= -P + 1 + y) {
        freept[x + Xoff][y + Yoff] = True;
      } else {
        freept[x + Xoff][y + Yoff] = False;
      }

      succpt[x + Xoff][y + Yoff][0] = Eos;
      succpt[x + Xoff][y + Yoff][1] = Eos;
    }
  }

  tHead = tTail = NULL; /* init linked list of 'tiles' */

  /* The initial untried stack (head) is (0,0), which is not free ... */

  freept[0 + Xoff][0 + Yoff] = False;
  recurse(0, 0, 0);

  printf("Tile counts = [");
  for (i = 1; i <= P; i++) {
    printf(" %d", t[i]);
  }
  printf(" ]\n");

  cofp = t[P];
  printf("Count of fixed polyominoes = %d\n", cofp);

  t2 = clock();
  printf("CPU time = %0.3fs\n", (double)(t2 - t1) / (double)CLOCKS_PER_SEC);

  printf("\n** Generating the polyomino positions **\n\n");

  copp = 0;
  genPosn();

  printf("Count of polyomino positions = %d\n", copp);

  /* In principle, it is not necessary to do this.  The DLX exact cover code
  will be unable to generate any covers if it selects an invalidly positioned
  polyomino.  So, we'll waste some time, but the results will be correct. */

  printf("\n** Eliminating the invalid polyomino positions **\n\n");

  tHead = pruning(tHead); // Removes invalid polyomino placements from
                          // selection.

  printf("starting cover count\n");

  if (P > 4) {
    build_heads3(); // Bucket sorts the valid polyomino placements.

    // Moves polyomino masks from linked lists to arrays for faster iteration.
    allocate_heads64();
    populate_heads64();
  } else {
    build_heads();
    int count = myGenCov0(0, 0);
    printf("Total unique covers: %d\n", count);
    return 0;
  }

  int children = 6;

  if (P == 7) {
    split_heads();
    children = 36;
  }

  printf("total valid polyomino positions: %d\n", totalPolys);

  ///
  // CHATGPT code start
  /*
  Used chatGPT to handle making the child processes because
  I couldn't be assed re-learning how to do it

  Prompt: in c code, how would you make multiple forks, all of which come to
  their own count of something, and then combine all of their counts once they
  are all finished?
  */
  int pipes[children][2];
  pid_t pid;

  // Create pipes
  for (int i = 0; i < children; i++) {
    if (pipe(pipes[i]) == -1) {
      perror("pipe");
      exit(1);
    }
  }

  for (int i = 0; i < children; i++) {
    pid = fork();

    if (pid == 0) {       // Child
      close(pipes[i][0]); // Close read end
      int count = 0;
      if (children == 36) { // This separation allows you to run P = 5 - 7;
        count = myGenCov3(i);
      } else {
        count = myGenCov2(i);
      }

      int wrote = write(pipes[i][1], &count, sizeof(count));
      if (wrote == -1) {
        perror("write");
        exit(1);
      }
      close(pipes[i][1]);
      exit(0);
    }
  }

  // Parent
  for (int i = 0; i < children; i++) {
    close(pipes[i][1]); // Close write end
  }

  // Wait and collect results
  for (int i = 0; i < children; i++) {
    wait(NULL);

    int child_result;
    int reads = read(pipes[i][0], &child_result, sizeof(child_result));
    if (reads == -1) {
      perror("read");
      exit(1);
    }
    close(pipes[i][0]);

    coverCount += child_result; // and this bit
  }
  /// End of ChatGPT code

  printf("Total unique covers: %d\n", coverCount);

  /* TBA */
  printf("TBA ... skipped, covp set to copp = %d\n", copp);
  covp = copp;

  /*printf("Count of valid positions = %d\n", covp);*/

  t2 = clock();
  printf("CPU time = %0.3fs\n", (double)(t2 - t1) / (double)CLOCKS_PER_SEC);
  return 0;

  /*
    printf("Sanity Check ... BEGIN\n");
    Poly *ptr;
    int cnt = 0;
    for (ptr = tHead; ptr != NULL; ptr = ptr->next)
      { cnt++; prtCells(ptr); }
    printf("cnt = %d  %s\n", cnt, cnt == covp ? "OK" : "NOT OK");
    printf("END ... Sanity Check\n");
  */

  printf("\n** Generating the distinct covers **\n\n");

  codc = 0;
  // genCov();

  printf("Count of distinct covers = %d\n", codc);

  t2 = clock();
  printf("CPU time = %0.3fs\n", (double)(t2 - t1) / (double)CLOCKS_PER_SEC);

  printf("\n");

  return EXIT_SUCCESS;
}
