
/* covers.c  :  5 Dec 24 .. 10 Dec 24  :  Colin Ramsay */

/* Ex
desk4-OptiPlex-9020/EXWORK/PC00328/Orig30Jun09/Archive1/poly/enum/enum2.c 
MyWork/tiles.c
*/

/** 
  Enumerating fixed polyominoes of size P (cf. tiles.c) is the first step in 
generating all polyomino covers of the PxP square.  This works, but the scaling 
is VERY bad.  We 'know' that t(n) grows as $n^{n^2}$.  If we wish to generate 
and process all covers, P=7 is probably the limit.  We can generate the cover up
to P=6 on-the-fly, but for P=7 we'll have to store them in a (big) file.
**/

#include <stdlib.h>          /* EXIT_SUCCESS ... */
#include <stdio.h>           /* printf() ... */
#include <time.h>            /* time() ... */

#include "exact.h"           /* for libexact */

////////////////////
////////////////////
#include <stdint.h>         //For using uint64_t type
#include <string.h>
///////////////////
///////////////////

#define  True   1
#define  False  0

#define  Pmin  1
#define  Pmax  9

#define  P  3                /* `target' tile size */

int tile[P][2];              /* the tile's x/y coords */
int t[P+1];                  /* count of (fixed) tiles */

int cofp, copp, covp;        /* counts FixedPoly, PolyPosition, ValidPos'n */
int codc;                    /* counts of DistinctCov */

//////////////////////////////
//////////////////////////////
uint64_t *biPolys = NULL;
int biSize = 0;
//////////////////////////////
//////////////////////////////

/* Note that x can run from -(P-2) to +(P-1) and y can run from 0 to +(P-1).  
With a 1 wide guard all round, we need -(P-1) .. +P and -1 .. +P.  So the 
indexing offsets are +(P-1) & +1.  We use -P as an end-of-stack value, since 
it's never used. */

int freept[2*P][P+2];        /* the free points - boolean */
int succpt[2*P][P+2][2];     /* the successor points - x/y */

#define  Xoff  (P-1)
#define  Yoff  1
#define  Eos   -P

/* PxP array for the current dissection, aka polyomino cover, aka tiling.  The
tiles are labelled arbitrarily 0..P-1. */

int tiling[P][P];

/* Poly struct stores the P cell numbers (0 to P^2-1) of a fixed polyomino in 
the PxP grid (aka tile), in some order.  A simple linked-list is used. 
TBA: dammit, need to lookup a Poly's cells. can we query the DLX array! */

typedef struct Poly
  {
  struct Poly *next;
  int cells[P];
  
    
  //////////////////
  //////////////////
  int binary_rep;
  //////////////////
  //////////////////

  }
Poly;

Poly *tHead, *tTail;

Poly *newPoly(void)
  {
  Poly *ptr;
  if ((ptr = (Poly*)malloc(sizeof(Poly))) == NULL)
    {
    printf("** Unable to malloc Poly struct in newPoly() **\n");
    exit(EXIT_FAILURE);
    }
  ptr->next = NULL;
  return ptr;
  }

////////////////////////////////////
////////////////////////////////////
/*converts binary of fixed polyomino into a string for DPS for validity checking.
Current solution built using using AI with prompt "In c code, how could I convert 
an integer into a string of its binary?" converted its solution to work in this code.*/

char* int_to_binary(uint64_t n) {
  int size = Pmax;
  char *string = malloc(Pmax + 1);

  if (string == NULL) {
    return NULL;
  }

  for (int i = size - 1; i >= 0; i--) {
    string[size - 1 - i] = (n & (1 << i)) ? '1' : '0';
  }

  string[size] = '\0';

  return string;
}

/*Performs a DFS search from the first 0 in the given string of binary. 
If the result is not a multiple of P, the fixed polynomial placement is invalid.
solution is modified from a solution generated by AI using the prompt "If I had a 
string that was representing a NxN grid (e.g. 010110000 for N = 3), how could I write 
a function that uses depth first search to find the number of reachable 0s starting 
from the first 0 in the string?"*/

int visited[Pmax][Pmax];
int dx[] = {-1, 1, 0, 0};
int dy[] = {0, 0, -1, 1};

int dfs (char* string, int x, int y) {

  if (x < 0 || x >= P || y < 0 || y>= P) {
    return 0;
  }

  if (visited[x][y]) {
    return 0;
  }
  if(string[x * P + y] != '0') {
    return 0;
  }
  visited[x][y] = 1;

  int count = 1;

  for (int dir = 0; dir < 4; dir++) {
    int nx = x + dx[dir];
    int ny = y + dy[dir];
    count += dfs(string, nx, ny);
  }

  return count;
}

int poly_valid(char *string) {
  int start = -1;
  for (int i = 0; i < Pmax; i++) {
    if (string[i] == '0') {
      start = i;
      break;
    }
  }

  if (start == -1) {
    return 0;
  }

  memset(visited, 0, sizeof(visited));

  int start_x = start / P;
  int start_y = start % P;

  int total = dfs(string, start_x, start_y);

  return total;

}


////////////////////////////////////
////////////////////////////////////


/* Note that both prtTile() & prtPoly() are only called on 'completed tiles' of
size P.  prtTile() prints the current tile[P][2] array, while prtPoly() prints
the given Poly struct. */

void prtTile(void)
  {
  int i,x,y;

  printf("# %2d\n", t[P]);             /* current count; ie, tile 'number' */
  for (y = P-1; y >= 0; y--)
    {
    for (x = -P+1; x <= P; x++)
      {
      if (y == 0 && x < 0)
        { printf(" -"); }
      else if (x >= 0 && y >= P-x)
        { printf(" -"); }
      else if (x < 0 && y >= P+x)
        { printf(" -"); }
      else
        {
        for (i = 0; i < P; i++)
          {
          if (tile[i][0] == x && tile[i][1] == y)
            {
            printf(" X");
            break;
            }
          }
        if (i == P) { printf("  "); }
        }
      }
    printf("\n");
    }
  }

void prtCells(Poly *ptr) 
  {
  int i,r,c;

  //////////////////////////////
  //////////////////////////////
  uint64_t biPoly = 0;
  //////////////////////////////
  //////////////////////////////

  printf(" +");
  for (c = 0; c < P; c++) { printf(" -"); }
  printf(" +\n");

  for (r = 0; r < P; r++)
    {
    for (c = -1; c <= P; c++)
      {
      if (c == -1 || c == P) { printf(" |"); }
      else
        {
        for (i = 0; i < P; i++)
          {
          if (r*P + c == ptr->cells[i])
            {
            biPoly = (biPoly << 1) | 1;
            printf(" X");
            break;
            }
          }
        if (i == P) { 
          biPoly <<= 1;
          printf(" ."); }
        }
      }
    printf("\n");
    }

  printf(" +");
  for (c = 0; c < P; c++) { printf(" -"); }
  printf(" +\n");
  biSize += 1;
  biPolys = realloc(biPolys, biSize * sizeof(uint64_t));
  biPolys[biSize - 1] = biPoly;
  }

/* Takes the linked list of (all/valid) polyomino positions, builds the exact
cover DLX problem, then generates all distinct covers.  Derived from the 
solveLatin*() routines in the MyWork/DLX2/scs*.c routines.  Our exact cover 
array has P^2 rows, one for each cell; ie, positions 0..P^2-1, in term or rows &
cols 0..P-1.  There are covp (currently = copp) cols, one for each of the Poly 
positions in the list, numbered 0..covp-1.  Each Poly col has P entries. */

void genCov(void)
  {
  int r,c, i,j, pCol;
  Poly *ptr;
  exact_t *e = exact_alloc();

  for (r = 0; r < P; r++)
    { for (c = 0; c < P; c++) { exact_declare_row(e, r*P + c, 1); } }

  for (ptr = tHead, pCol = 0; ptr != NULL; ptr = ptr->next, pCol++)
    {
    exact_declare_col(e, pCol, 1);
    for (i = 0; i < P; i++)
      { exact_declare_entry(e, ptr->cells[i], pCol); }
    }
  
  int stk;  
  const int *b;

  /* This is ... a bit of a kludge.  We need to have some sort of col to covered
  rows lookup table.  ?Build this when we're setting up the problem. */

  while ((b = exact_solve(e, &stk)) != NULL) 
    { 
    codc++;

    printf("codc=%d, b[0..%d] =", codc, stk);
    for (i = 0; i < stk; i++)
      { 
      printf(" %d", b[i]);
      for (j = 0; j < P*P; j++)
         {
         if (exact_is_entry(e, j, b[i]) == 1) 
           { tiling[j/P][j%P] = i; }
         }
      }
    printf("\n");
    for (r = 0; r < P; r++)
      {
      for (c = 0; c < P; c++)
        /*{ printf(" %d", tiling[r][c]); }*/
        { printf(" %c", 'A' + tiling[r][c]); }
      printf("\n");
      }
    }

  exact_free(e);
  }

/* 
  Function chkPoly() return True iff the Poly position is valid ... TBA
Will be used (maybe) to filter out invalid positions from the list.
*/

int chkPosn(Poly *ptr)
  {
  /* TBA */
  return True;
  }

/* 
  Takes tHead/tTail and builds new list of all possible positions of all fixed
polyominoes (these are NOT checked for validity at this stage).  This list 
'replaces' the original.  The positions are straightforward.  For each fixed 
Poly the top row & left col are both 0 (by construction), we need bottomrow & 
rightcolumn (br, rc).  Now easy to generate all possible placements.
  Note that the original tHead/tTail list will be 'replaced' by the new list,
with each of the original fixed Poly being followed by its 'children' (some of
which may be 'invalid').  The original list ie deallocated as we go.
*/

void genPosn(void)
  {
  Poly *ptr, *newH, *newT, *pTmp;      /* NB: pTmp does double duty! */
  int br, rc;
  int i, j, k, r, c;

  newH = newT = NULL;
  pTmp = NULL;

  for (ptr = tHead; ptr != NULL; ptr = ptr->next)
    {
    if (pTmp != NULL) { free(pTmp); }

    /* Get the tile's bounding rectangle */
    br = 0;
    rc = 0;
    for (i = 0; i < P; i++)
      { 
      j = ptr->cells[i];
      if (j/P > br) { br = j/P; }
      if (j%P > rc) { rc = j%P; }
      }
    /*printf("br=%d rc=%d\n", br, rc);*/

    /* Iterate over all possible positions, incl the 'fixed' position */
    for (r = 0; r < P - br; r++)
      {
      for (c = 0; c < P - rc; c++)
        {
        pTmp = newPoly(); 
        for (k = 0; k < P; k++)
          { pTmp->cells[k] = ptr->cells[k] + r*P + c; }
        copp++;
        printf("Position %d\n", copp-1);
        prtCells(pTmp);

        /////////////
        /////////////
        ptr->binary_rep = biPolys[biSize - 1];
        /////////////
        /////////////

        if (newH == NULL) 
          { newH = newT = pTmp; }
        else
          { newT->next = pTmp;  newT = pTmp; }
        pTmp = NULL;
        
        }
      }

    pTmp = ptr;
    }

  if (pTmp != NULL) { free(pTmp); }
  tHead = newH;
  tTail = newT;
  }

/**
  Function logTile() processes the new current tile[P][2], of size P.
  In the tiles.c code, cell's coords are (X,Y) with the origin (0,0) and X incr
to the right and Y upwards.  For fixed polyominoes in the PxP square the ref'ce
position is as far up and to the left as possible.  The coords are (R,C) with
the origin (0,0) and C incr to the right and R downwards.  So X becomes C and Y
becomes R.  The least X has to become C=0: ie, C = X - min(set of X).  We have
to invert the order for Y, with the maximum Y becoming R = 0. 
  With the polyomino in our standard position we convert the xP R/C coord pairs 
to cell numbers (in 0..P^2-1) and add it to our linked list of "fixed 
polyominoes in reference position".  Note that the cell numbers may not be in
incr order (this does not matter?).
**/

void logTile(int tsiz)
  {
  int i, x, y, r, c;
  int minX = P, maxY = -1;
  Poly *ptr;

  /*printf("# %2d : X/Y ", t[tsiz]);*/
  for (i = 0; i < tsiz; i++)
    {
    x = tile[i][0];
    y = tile[i][1];
    /*printf(" (%d,%d)", x, y);*/
    if (x < minX) { minX = x; }
    if (y > maxY) { maxY = y; }
    }
  /*printf(" : minX=%d maxY=%d\n", minX, maxY);*/

  ptr = newPoly();

  /*printf("# %2d : R/C ", t[tsiz]);*/
  for (i = 0; i < tsiz; i++)
    {
    x = tile[i][0];
    y = tile[i][1];
    c = x - minX;
    r = maxY - y;
    /*printf(" (%d,%d)", r, c);*/
    ptr->cells[i] = r*P + c;
    }
  /*printf("\n");*/

  if (tHead == NULL) 
    { tHead = tTail = ptr; }
  else
    { tTail->next = ptr;  tTail = ptr; }

  /*prtTile();*/
  /*prtCells(ptr);*/
  }

/* tsiz is the size of the current tile at entry, and is thus the index for the 
point(s) to be added.  x/y are the point at the head of the untried stack. */

void recurse(int tsiz, int x, int y)
  {
  int ix,iy,tx,ty,cx,cy;
  int tl,tr,tu,td;

  /* Repeat until the untried set is exhausted ... */

  ix = x;
  iy = y;
  while (ix != Eos && iy != Eos)
    {

  /* 1. Remove an (arbitrary) element from the untried set ... */

    cx = succpt[ix+Xoff][iy+Yoff][0];
    cy = succpt[ix+Xoff][iy+Yoff][1];

  /* 2. Place a cell at this point ... */

    tile[tsiz][0] = ix;
    tile[tsiz][1] = iy;

  /* 3. Count this new polynomio, process if size P ... */

    t[tsiz+1]++;

    if (tsiz == P - 1)
      {
      /*printf("\n");*/
      logTile(tsiz+1);
      }

  /* 4. If the size is less than P ... */

    if (tsiz < P-1)
      {

  /* (a) Add *new* neighbours to the untried set ... */

      if (freept[ix+Xoff][iy+Yoff + 1])
        {
        succpt[ix+Xoff][iy+Yoff + 1][0] = cx;
        succpt[ix+Xoff][iy+Yoff + 1][1] = cy;
        cx = ix;
        cy = iy + 1;

        freept[cx+Xoff][cy+Yoff] = False;
        tu = True;
        }
      else
        { tu = False; }
      if (freept[ix+Xoff + 1][iy+Yoff])
        {
        succpt[ix+Xoff + 1][iy+Yoff][0] = cx;
        succpt[ix+Xoff + 1][iy+Yoff][1] = cy;
        cx = ix + 1;
        cy = iy;

        freept[cx+Xoff][cy+Yoff] = False;
        tr = True;
        }
      else
        { tr = False; }
      if (freept[ix+Xoff - 1][iy+Yoff])
        {
        succpt[ix+Xoff - 1][iy+Yoff][0] = cx;
        succpt[ix+Xoff - 1][iy+Yoff][1] = cy;
        cx = ix - 1;
        cy = iy;

        freept[cx+Xoff][cy+Yoff] = False;
        tl = True;
        }
      else
        { tl = False; }
      if (freept[ix+Xoff][iy+Yoff - 1])
        {
        succpt[ix+Xoff][iy+Yoff - 1][0] = cx;
        succpt[ix+Xoff][iy+Yoff - 1][1] = cy;
        cx = ix;
        cy = iy - 1;

        freept[cx+Xoff][cy+Yoff] = False;
        td = True;
        }
      else
        { td = False; }

  /* (b) Call this algorithm recursively ... */

      recurse(tsiz+1, cx,cy);

  /* (c) Remove the new neighbours from the untried set ... */

      if (td)
        { 
        freept[cx+Xoff][cy+Yoff] = True;

        tx = succpt[cx+Xoff][cy+Yoff][0];
        ty = succpt[cx+Xoff][cy+Yoff][1];
        cx = tx;
        cy = ty;
        }
      if (tl)
        {
        freept[cx+Xoff][cy+Yoff] = True;

        tx = succpt[cx+Xoff][cy+Yoff][0];
        ty = succpt[cx+Xoff][cy+Yoff][1];
        cx = tx;
        cy = ty;
        }
      if (tr)
        {
        freept[cx+Xoff][cy+Yoff] = True;

        tx = succpt[cx+Xoff][cy+Yoff][0];
        ty = succpt[cx+Xoff][cy+Yoff][1];
        cx = tx;
        cy = ty;
        }
      if (tu)
        {
        freept[cx+Xoff][cy+Yoff] = True;

        tx = succpt[cx+Xoff][cy+Yoff][0];
        ty = succpt[cx+Xoff][cy+Yoff][1];
        cx = tx;
        cy = ty;
        }
      }

  /* 5. Remove newest cell ... */

    /* n/a */

    tx = succpt[ix+Xoff][iy+Yoff][0];
    ty = succpt[ix+Xoff][iy+Yoff][1];
    ix = tx;
    iy = ty;
    }
  }

int main(void)
  {
  int i, x,y;
  clock_t t1, t2;

  if (P < Pmin || P > Pmax)
    {
    printf("\n** tile size must be in %d-%d **\n\n", Pmin, Pmax);
    exit(EXIT_FAILURE);
    }

  t1 = clock();

  printf("\n** Generating the fixed polyominoes **\n\n");

  printf("Tile size = %d\n", P);

  for (i = 1; i <= P; i++)
    { t[i] = 0; }

  for (x = -P+1; x <= P; x++)
    {
    for (y = -1; y <= P; y++)
      {
      if (y >= 0 && x >= 0 && x <= P-1-y)
        { freept[x+Xoff][y+Yoff] = True; }
      else if (y >= 1 && x < 0 && x >= -P+1+y)
        { freept[x+Xoff][y+Yoff] = True; }
      else
        { freept[x+Xoff][y+Yoff] = False; }

      succpt[x+Xoff][y+Yoff][0] = Eos;
      succpt[x+Xoff][y+Yoff][1] = Eos;
      }
    }

  tHead = tTail = NULL;           /* init linked list of 'tiles' */

  /* The initial untried stack (head) is (0,0), which is not free ... */

  freept[0+Xoff][0+Yoff] = False;
  recurse(0,0,0);

  printf("Tile counts = [");
  for (i = 1; i <= P; i++)
    { printf(" %d", t[i]); }
  printf(" ]\n");

  cofp = t[P];
  printf("Count of fixed polyominoes = %d\n", cofp);

  t2 = clock();
  printf("CPU time = %0.3fs\n", (double)(t2-t1)/(double)CLOCKS_PER_SEC);

  printf("\n** Generating the polyomino positions **\n\n");

  copp = 0;
  genPosn();

  printf("Count of polyomino positions = %d\n", copp);

  t2 = clock();
  printf("CPU time = %0.3fs\n", (double)(t2-t1)/(double)CLOCKS_PER_SEC);

  /* In principle, it is not necessary to do this.  The DLX exact cover code 
  will be unable to generate any covers if it selects an invalidly positioned
  polyomino.  So, we'll waste some time, but the results will be correct. */

  printf("\n** Eliminating the invalid polyomino positions **\n\n");

  //////////////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////
  printf("PRINTING biPolys!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");

  for (int i = 0; i < biSize; i++) {
    if (poly_valid(int_to_binary(biPolys[i])) % P != 0) {
      printf("%ld\n", biPolys[i]);
      //NEED TO REMOVE RESPECTIVE POLY FROM POLYSTRUCT
    }
  }

  ////////////////////////////////
  ////////////////////////////////

  /* TBA */
  printf("TBA ... skipped, covp set to copp = %d\n", copp);
  covp = copp;

/*printf("Count of valid positions = %d\n", covp);*/

  t2 = clock();
  printf("CPU time = %0.3fs\n", (double)(t2-t1)/(double)CLOCKS_PER_SEC);

/*
  printf("Sanity Check ... BEGIN\n");
  Poly *ptr;
  int cnt = 0;
  for (ptr = tHead; ptr != NULL; ptr = ptr->next)
    { cnt++; prtCells(ptr); }
  printf("cnt = %d  %s\n", cnt, cnt == covp ? "OK" : "NOT OK");
  printf("END ... Sanity Check\n");
*/

  printf("\n** Generating the distinct covers **\n\n");

  codc = 0;
  genCov();

  printf("Count of distinct covers = %d\n", codc);

  t2 = clock();
  printf("CPU time = %0.3fs\n", (double)(t2-t1)/(double)CLOCKS_PER_SEC);

  printf("\n");

  return EXIT_SUCCESS;
  }


